[package]
name = "rust_chat"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "server"
path = "./src/server.rs"

[[bin]]
name = "client"
path = "./src/client.rs"

[[bin]]
name = "pandora"
path = "./src/pandora.rs"

[dependencies]
crossterm = "0.29.0"
getrandom = "0.3.4"
rustls = "0.23.35"
mio = { version = "0.8.10", features = ["os-poll", "net"] }
